import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import ReduxProvider from "@/providers/ReduxProvider";
import PersistProvider from "@/providers/PersistProvider";
import Footer from "@/components/Footer";
import Navbar from "@/components/navbar/Navbar";
import Header from "@/components/header/Header";
import MaxWidthWrapper from "@/components/MaxWidthWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "kamovie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <PersistProvider>
            <ReactQueryProvider>
              <MaxWidthWrapper className="">
              <Header/>
              <Navbar/>
              {children}
              <Footer />
              </MaxWidthWrapper>
            </ReactQueryProvider>
          </PersistProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}


// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <ReduxProvider>
//           <PersistProvider>
//         <ReactQueryProvider>
//         {children}
//           </PersistProvider>
//         </ReactQueryProvider>
//         <Footer/>
//           </PersistProvider>
//         </ReduxProvider>
//       </body>
//     </html>
//   );
// }
