name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, "*" ]
  pull_request:
    branches: [ main, master ]
  pull_request_review:
    types: [submitted]

permissions:
  contents: read
  issues: write
  pull-requests: write   
  checks: write   

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm test -- --coverage --watchAll=false
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            .next
            package.json
            package-lock.json
            next.config.*

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .

      - name: Deploy to Vercel
        id: vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-args: >-
            ${{ (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')) && '--prod --confirm' ||
                (github.event_name == 'pull_request_review' && github.event.review.state == 'approved') && '--prod --confirm' ||
                '--confirm' }}

      - name: Comment PR with Preview URL
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: preview-url
          message: |
             Vercel Preview is ready!
             [View Deployment](${{ steps.vercel.outputs.preview-url }})

      - name: Update GitHub Check with Deployment URL
        if: always() # make sure it runs even if previous step skipped
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const deploymentUrl = "${{ steps.vercel.outputs.preview-url }}";
            const conclusion = deploymentUrl ? "success" : "failure";

            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "Deployed to Vercel",
              head_sha: context.sha,
              status: "completed",
              conclusion,
              output: {
                title: "Deployment Complete",
                summary: deploymentUrl 
                  ? `Deployed successfully: [View Deployment](${deploymentUrl})` 
                  : "Deployment failed."
              }
            });
